---
- hosts: all
  become: true

  tasks:
    - name: yum install nginx
      yum: 
        name: nginx
        state: present
    - name: setup nginx 
      systemd:
        name: nginx
        state: restarted
        enabled: true
    - name: firewalld
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: copy sample html
      copy:
        src: ../files/{{ item.name }}
        dest: /usr/share/nginx/html/{{ item.name }}
        mode: 0644
        group: root
        owner: root
      with_items:
        - name: bootstrap-01.html
        - name: bootstrap-02.html
