---
- hosts: all
  become: true

  tasks:
    - name: yum install nginx
      yum: 
        name: nginx
        state: present
    - name: setup nginx 
      systemd:
        name: nginx
        state: restarted
        enabled: true
    - name: firewalld
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: test.html
      copy:
        src: ../files/test.html
        dest: /usr/share/nginx/html/test.html
        mode: 0644
        group: root
        owner: roo
