---
#
# https://qiita.com/ksugawara61/items/e3bb87d5e0dd49d20c8f
# 

- name: yum install
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - gcc
    - gcc-c++
    - openssl-devel
    - readline-devel  
